### ISSUE TITLE
Property parsing error

### ISSUE THREAD

**Issue by REDxEYE** [maxdup/fgd-tools#4]
Entity property parsed wrong
Entity data (TF2 fgd):
`
@PointClass base(Targetname) size(-8 -8 -8, 8 8 8) = logic_navigation : 
	"An entity that is used to set navigation properties on other entities. Useful to make NPCs ignore physics props in their way that they can easily push." 
[
	target(target_destination) : "Navigation Entity" : "Name of the entity to set navigation properties on."
	spawnflags(flags) =
	[
		1 : "Start On" : 1
	]
	navprop(choices) : "Nav Property" : "Ignore" =
	[
		"Ignore" : "NPCs Ignore this when navigating (they'll bump into it)"
	]
	
	// Inputs
	input TurnOn(void) : "Turn on. The Navigation Entity will have its navigation properties set."
	input TurnOff(void) : "Turn off. The Navigation Entity will have its navigation properties returned to the default settings."
	input Toggle(void) : "Toggle on/off."
]
`

Entity property in question: `target(target_destination) : "Navigation Entity" : "Name of the entity to set navigation properties on."`. `Name of the entity to set navigation properties on.` is parsed as default value instead of documentation string

**Comment by maxdup** [comment]
I will look into this. 

Just letting you know, Fgd-tools is in the process of becoming deprecated in favor of valveFGD. It is the same project, just rebranded, and under a new organisation for similar projects. https://github.com/pySourceSDK/ValveFGD
The next fgd-tools update will only be a deprecation warning. The fix for this issue will be applied to ValveFGD

I recommend switching now, migrating will not require any work other than switching the package name.

**Comment by maxdup** [comment]
Alright, so, I understand that this string was probably intended as documentation but...
While this may or may not be intended, Hammer parses it as a default value.
This library aims to be consistent with Hammer. This means replicating its behavior (and bugs) as closely as possible.

This behavior will not be changed, sorry for the inconvenience

**Comment by REDxEYE** [comment]
Is it possible to add a parameter to toggle between hammer behaviour and correct behaviour? I'm using this library to parse and generate a bunch of python classes to deserialize bsp entities into objects

**Comment by maxdup** [comment]
So it's clear that the shipped fgd files and hammer sometimes disagree on the FGD spec, who's at fault? Hard to say. Having not found a spec for FGD files, I have to assume the shipped fgd files are faulty. I will not be implementing support for things that, until proven wrong, are mistakes. If you can find specification about the FGD file format that I can implement, I might add support for it. Otherwise my advise will be to fix your fgd files (probably by removing the comment strings).
